### ISSUE TITLE
Improve implementation of ColumnDataSource

### ISSUE THREAD

**Issue by ahaym** [ahaym/boke-hs#4]
Currently ColumnDataSource uses an unvalidated `[(Field, [Scientific])` as its data store; a different implementation would surely be more performant, safe, and easier to use. By @ocramz' suggestion, `Frames` is the current best candidate.

**Comment by ocramz** [comment]
Hi @ahaym , I invited you to join the DataHaskell GH org and forked `boke-hs` over there. I'd like to add `Frames` for the data representation, `colour` instead of using an ad-hoc sum type and in general add a bunch of abstractions to produce more complex plots.

**Comment by ahaym** [comment]
For the `DataSource` representation, I suppose my idea is that the user shouldn't be allowed to touch `DataSource`, and should just use abstractions to generate the plot. In this regard having `Frames` as the implementation of `CDS` sounds like a good idea, though I would like to be able to create plots both with and without `Frames` on the user end. it would look like 
`Graphics.BokeHS.Arrays.addLine :: (Num a, Num b) => Plot -> Array (a,b) -> Plot` 
and,
`Graphics.BokeHS.Frames.addLine :: (Num a, Num b) => Plot -> Frame r -> Lens r a -> Lens r b -> Plot`

@ocramz what do you think?

Edit: Actually, doesn't `addLine :: Foldable t => Plot -> t r -> (r -> Scientific) -> (r -> Scientific) -> Plot work as a method that subsumes all of these?

**Comment by ahaym** [comment]
okay for now, may reopen later
